apiVersion: apps/v1
kind: Deployment
metadata:
  name: rankrent-be
spec:
  selector:
    matchLabels:
      app: rankrent-be
  template:
    metadata:
      labels:
        app: rankrent-be
    spec:
      containers:
        - name: rankrent-be
          image: sasha444/rankrent-be:latest
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rankrent-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rankrent-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rankrent-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rankrent-secrets
                  key: DB_NAME
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: rankrent-be
spec:
  selector:
    app: rankrent-be
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP
